### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by guagsak** [nitaybz/homebridge-broadlink-s1c#2]
I am getting this error when I use "sudo npm install -g homebridge-broadlink-s1c"

```
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nitaybz/broadlinkjs-s1c.git /root/.npm/_cacache/tmp/git-clone-f2af2856
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-f2af2856': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-13T15_42_10_915Z-debug.log
```

Anyone got the same issue? or how to fix it?

**Comment by nitaybz** [comment]
what npm version do you use?

**Comment by nitaybz** [comment]
Anyway, this issue happens on npm version > 5
it's not just with this plugin, anything you'll try to install will act the same.
please reinstall npm version 4.6,
this version is more stable now... at least until they will figure this out.

**Comment by guagsak** [comment]
Thank you for your fast reply. I used the npm v. 5.0.3.

I have downgraded to v. 4.6.1, and everything works perfectly. Thank you very much.
