### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aksneo** [nitaybz/homebridge-broadlink-s1c#5]
hi.
i can't install my raspberry pi.

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nitaybz/broadlinkjs-s1c.git /root/.npm/_cacache/tmp/git-clone-e78b31b9
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e78b31b9': Erişim engellendi
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-28T20_26_11_065Z-debug.log
pi@raspberrypi:~ $

**Comment by aksneo** [comment]
please update this plugin

**Comment by nitaybz** [comment]
hey @aksneo 
the problem you describing is caused by npm version 5.3
I use npm version 4.6.1 and it works perfectly... you can install old npm version like this:
`sudo npm install -g npm@4.6.1`

after running that try to install again

**Comment by aksneo** [comment]
@nitabyz
thanks for help
i can't solve the problem about 2 weeks. now i can use perfectly

do you use broadlink tc2 and broadlink rm pro ?

**Comment by nitaybz** [comment]
yes I do, also SP and MP1
