### ISSUE TITLE
Broadlink S2

### ISSUE THREAD

**Issue by CiTroNaK** [nitaybz/homebridge-broadlink-s1c#9]
Could someone please test it with the new version Broadlink S2?

Thank you very much.

Petr

**Comment by pazax** [comment]
Not working for me with 2 door sensors. When I used S2 with 1 door sensor, it worked fine. After adding the 2nd door sensor, the status keep switching between "closed" and "opened" for both. I gave up using the plugin. It will be very useful for the fix btw.
